name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [master]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update sponsors
        run: npx sponsorkit -w 800 --dir . && npx sponsorkit -w 1300 --name sponsors.wide --dir ./public
        env:
          SPONSORKIT_TOKEN: ${{ secrets.SPONSORS_GITHUB_TOKEN }}
          SPONSORKIT_LOGIN: YunYouJun

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore: update sponsors.svg"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
